version: "3.1"

language: "pl"

pipeline:
- name: SpacyNLP
  model: pl_core_news_md
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  fallback_classification_threshold: 0.3
  max_sequence_length: 256
- name: EntitySynonymMapper

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: TEDPolicy
  max_history: 5
  epochs: 100

assistant_id: 20250416-155937-numerous-feta
